apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: renandotcorrea/go-micro-auth:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: auth-configmap
            - secretRef:
                name: auth-secret